config/routes.rb
Bookshop::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :clients
  resources :users, :only => [:new, :create]


  root :to => 'home#index'
    match '/about_company', :to => 'home#about_company'
    match '/contact_us', :to => 'home#contact_us'
    match '/cooperation', :to => 'home#cooperation'
#  match "/contact_us", :to => "contacts#new"

  resources :contacts, :only => [:new, :create]
  resources :books, :only => [:index, :show]
  resources :games, :only => [:index, :show]
  resources :accessories, :only => [:index, :show]
  resources :category_books, :only => [:index, :show]
  resources :subcategory_books, :only => [:show]
  resources :category_games, :only => [:index, :show]
  resources :subcategory_games, :only => [:show]
  resources :category_accessories, :only => [:index, :show]
  resources :publisher_books, :only => [:index, :show]
  resources :publisher_games, :only => [:index, :show]


  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/category_game.rb
class CategoryGame < ActiveRecord::Base
  has_many :subcategory_games
  has_many :games
  validates_uniqueness_of :name
end

app/controllers/category_games_controller.rb
class CategoryGamesController < ApplicationController
  def index
    @category_games = CategoryGame.all 
  end

  def show
    @category_game = CategoryGame.find(params[:id])
    @games = @category_game.games.page(params[:page]).per(10) 
  end

  def new 
    @category_game = CategoryGame.new
  end

  def create
    @category_game = CategoryGame.new(params[:category_game])
    if @category_game.save
      redirect_to category_game_path(@category_game)
    else
      render :action => "new"
    end
  end

  def edit
  end

  def destroy
  end

end

app/helpers/category_games_helper.rb
module CategoryGamesHelper
end

app/views/category_games/index.html.haml
- for category_game in @category_games 
  %h2.name
    = link_to category_game.name, category_game_path(category_game)

app/views/category_games/show.html.haml
%h3.title Podkategorie:
- for subcategory_game in @category_game.subcategory_games 
  %h2.title
    = link_to "#{subcategory_game.name} (#{subcategory_game.games.length})", subcategory_game_path(subcategory_game)
%h3.title Gry:
- for game in @games 
  .post
  %h2.title
    = link_to game.name, game_path(game)
    - unless game.product.pictures.blank?
      %br/
      = image_tag game.product.pictures.first.photo.url(:thumb)
    %p.tekst-1strona
      gatunek gry: #{game.game_type}
      %br/
      opis: #{truncate(game.description, :length => 20, :separator => ' ', :ommission => "...")}
      %br/
      cena: #{number_to_currency(game.price)}
%br/
%br/
= paginate @games