config/routes.rb
Bookshop::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :clients
  resources :users, :only => [:new, :create]


  root :to => 'home#index'
    match '/about_company', :to => 'home#about_company'
    match '/contact_us', :to => 'home#contact_us'
    match '/cooperation', :to => 'home#cooperation'
#  match "/contact_us", :to => "contacts#new"

  resources :contacts, :only => [:new, :create]
  resources :books, :only => [:index, :show]
  resources :games, :only => [:index, :show]
  resources :accessories, :only => [:index, :show]
  resources :category_books, :only => [:index, :show]
  resources :subcategory_books, :only => [:show]
  resources :category_games, :only => [:index, :show]
  resources :subcategory_games, :only => [:show]
  resources :category_accessories, :only => [:index, :show]
  resources :publisher_books, :only => [:index, :show]
  resources :publisher_games, :only => [:index, :show]


  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_company.html.haml
%p Szanowni Państwo.
%p Centrum Dobrej Książki i Gry powstało z myślą o niezwykle  zróżnicowanych potrzebach klientów. Doskonale zdajemy sobie sprawę, że niema  dwóch takich samych odbiorców i dlatego staramy się dopasować ofertę  indywidualnie pod kątem spersonalizowanych wymagań i potrzeb. Dzięki takiej  filozofii firmy, mogą Państwo pouczyć się w trakcie zakupów w naszej firmie  naprawdę wyjątkowo.
%p Klientami naszej firmy są biblioteki, szkoły, instytucje i  firmy o różnych profilach działalności oraz klienci indywidualni poszukujący  unikatowych i wartościowych pozycji.
%p Warto pamiętać iż na życzenie klientów wyszukujemy i  sprowadzamy wybrane i poszukiwane tytuły.
%p Centrum Dobrej Książki i Gry oferuje również swoim klientom  gry planszowe. Począwszy od prostych gier edukacyjnych poprzez towarzyskie,  ekonomiczne, strategiczne i bitewne aż po rzadkie edycje kolekcjonerskie.  Dzięki oferowanym grom możemy nie tylko się zrelaksować ale także przenieść w  inny świat i samemu tworzyć fabułę gry, gdzie czasami jedynymi ograniczeniami  dla gry są tylko granice naszej wyobraźni. Proponowane przez nas gry są zawsze  dobierane stosownie do wieku, temperamentu, doświadczenia i zainteresowań co w  dużej mierze gwarantuje satysfakcję.
%p Zachęcamy do regularnego odwiedzania naszej strony i  śledzenia nowości wydawniczych.

app/views/home/contact_us.html.haml
/ @page { size: 21cm 29.7cm; margin: 2cm }  		P { margin-bottom: 0.21cm }  		A:link { color: #000080; so-language: zxx; text-decoration: underline }
%BODY{:DIR => "LTR", :LINK => "#000080", :VLINK => "#800000"}
  %p Doskonale wiemy iż nie tylko rynek wydawniczy się zmienia  ale także Państwa oczekiwania. Jeśli czegoś Państwu brakuje w naszej ofercie  lub chcielibyście się Państwo podzielić opinią czy sugestią, zachęcamy do  skorzystania z elektronicznego formularza kontaktowego. 
  %p
    = link_to "Formularz kontaktowy", new_contact_path 
  %p 
    Bądźmy zawsze w kontakcie
    %br/ 
    Tel. (34) 343 03 23
    %br/
    Kom. 669 73 24 32 
    %br/
    Fax. (34) 343 00 32
    %br/
    e-mail: biuro@cdkig.pl
  %p 
    Dane firmy:
    %br/
    Centrum Dobrej Książki i Gry
    %br/
    ul. Olsztyńska 85/1
    %br/
    42-202 Częstochowa
    %br/
    NIP 949-189-93-96
  %p{:align => "center"}

app/views/home/cooperation.html.haml
%p 
Szanowni Państwo!
%br
Jeśli jesteście zainteresowani współpracą z Centrum Dobrej  Książki i Gry zachęcamy do skorzystania z elektronicznego formularza  kontaktowego.
%br
Jesteśmy do Państwa dyspozycji również pod telefonem o numerze (34) 343 03 23 w godzinach 8-16 oraz pod numerem  669 73 24 32 o dowolnej porze.
%p{:align => "left"} 

app/views/home/index.html.haml
%p{:style => "font-weight: bold; font-size: 16px;"} Witamy na stronie Centrum Dobrej Książki i Gry
%p Na łamach tej witryny odnajdziecie Państwo nie tylko opisy  nowości wydawniczych czy wyszukacie edycje bibliofilskie. W Centrum Dobrej  Ksiązki i Gry można również odnaleźć doskonałe pomysły na prezenty dla bliskich  Wam osób czy kluczowych klientów i pracowników . Pamiętajmy iż upominki którymi  obdarowywujemy innych świadczą o nas samych. Stąd odpowiednio dobrana książka  czy gra planszowa mogą sprawić wiele radości bliskim a wśród obdarowywanych  kontrahentów i pracowników utrwali pozytywny wizerunek firmy również jako  mecenasa kultury. Asortyment który oferujemy Państwu, to książki z  najznakomitszych polskich wydawnictw, często z głęboko zakorzenioną tradycją i  bogatą historią co czyni ofertę wyjątkową .
%p  
%p{:style => "font-weight: bold; font-size: 16px;"}Serdecznie zapraszamy i zachęcamy do szczegółowego  zapoznania się z naszą bogatą ofertą


-#%h1 Logowanie
-#- if user_signed_in?
-#	Witaj,
-#	= current_user.email
-#	= link_to "Wyloguj", destroy_user_session_path, :method => "delete"
-#- else
-#	= link_to "Zaloguj", new_user_session_path