config/routes.rb
Bookshop::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :clients
  resources :users, :only => [:new, :create]


  root :to => 'home#index'
    match '/about_company', :to => 'home#about_company'
    match '/contact_us', :to => 'home#contact_us'
    match '/cooperation', :to => 'home#cooperation'
#  match "/contact_us", :to => "contacts#new"

  resources :contacts, :only => [:new, :create]
  resources :books, :only => [:index, :show]
  resources :games, :only => [:index, :show]
  resources :accessories, :only => [:index, :show]
  resources :category_books, :only => [:index, :show]
  resources :subcategory_books, :only => [:show]
  resources :category_games, :only => [:index, :show]
  resources :subcategory_games, :only => [:show]
  resources :category_accessories, :only => [:index, :show]
  resources :publisher_books, :only => [:index, :show]
  resources :publisher_games, :only => [:index, :show]


  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/category_book.rb
class CategoryBook < ActiveRecord::Base
  has_many :subcategory_books
  has_many :books
  validates_uniqueness_of :name
end

app/controllers/category_books_controller.rb
class CategoryBooksController < ApplicationController
  def index
    @category_books = CategoryBook.all 
  end

  def show
    @category_book = CategoryBook.find(params[:id])
    @books = @category_book.books.page(params[:page]).per(10) 
  end

  def new 
    @category_book = CategoryBook.new
  end

  def create
    @category_book = CategoryBook.new(params[:category_book])
    if @category_book.save
      redirect_to category_book_path(@category_book)
    else
      render :action => "new"
    end
  end

  def edit
  end

  def destroy
  end

end

app/helpers/category_books_helper.rb
module CategoryBooksHelper
end

app/views/category_books/index.html.haml
- for category_book in @category_books 
  %h2.name
    = link_to category_book.name, category_book_path(category_book)

app/views/category_books/show.html.haml
%h3.title Podkategorie:
- for subcategory_book in @category_book.subcategory_books 
  %h2.title
    = link_to "#{subcategory_book.name} (#{subcategory_book.books.length})", subcategory_book_path(subcategory_book)
%h3.title Książki:
- for book in @books 
  .post
  %h2.title
    = link_to book.title, book_path(book)
    - unless book.product.pictures.blank?
      %br/
      = image_tag book.product.pictures.first.photo.url(:thumb)
    %p.tekst-1strona
      Autor: #{book.author}
      %br/
      Wydawnictwo:
      = link_to book.publisher_book.name, publisher_book_path(book.publisher_book_id) 
      %br/
      rok wydania: #{book.year_of_publishing} 
      %br/
      rodzaj oprawy:  #{book.cover}
      %br/
      cena: #{number_to_currency(book.price)} 
%br/
%br/
= paginate @books